import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import { useMousePos } from "../hooks/useMousePos";

const Main = styled.main`

  -webkit-filter:blur(5px) contrast(30);
  filter:blur(10px) contrast(30);

  background: white;
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;

  :root {
    --mouseX: 0;
  }
`

const Title = styled.h1`
  font-size: 13vw;
  margin: 0;
`

const Box = styled.div`
  width: 10vw;
  height: 10vw;
  border-radius: 50%;
  background-color: black;
  position: fixed;
  left: var(--mouseX);
  top: var(--mouseY);
  transform: translate(-50%, -50%);
`

const Layer = styled.div`
  position: fixed;
  width: 100%;
  height: 100%;
  background-color: #613336;
  z-index: 2;
  mix-blend-mode: multiply;
`

export default function Home() {
  const { posX, posY } = useMousePos();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <Main>
          <Title>DAMA</Title>

          <Box style={{"--mouseX": posX + "px", "--mouseY": posY + "px", }}/>
        </Main>

        <Layer />
    </div>
  )
}
